sudo: required
language: node_js

env:
global:
- secure: "h7wiFdUXs7W+wmTbl6YVcYu3iJz7cxp5rk2uc0G0jjrOTX4tj6sCINIUtdWSxz3uNMHNaJGrmIc9GtIn0gqfpuw592zQdpBGf88J7kJMF7mC+UzmViFg/Vnt6dY2WlU7/5nUUpJl6SY/ihUSUeFYwJiO4DfeqCEcne9ywVFbk1lsykVc0OF83RIbg5EzYkpmhLz4zpFbpDkkFaaR7eaKZUjcVLj82RNWA4InLWj8fcvpFhjVFgpcXrk1ZW4YAkOJwqbc6WI15RBpFZD0+bCI3QlFXR2laWPzp8e0x4Is7OYKUe9h1iQDpveD+20xE2xy6sZT+aAIqOhZ6bNL3UrEsKOk+lqQtD0QOQVf562SHhdjyHjsQXfdSc4uG6yOCgRjkaCu0qkhq/tV6woDL/jDcd45G5RXeJoY7c8n/M1ucnaSAMe5FI2/LYo4y0VFYmFkrA9k8pyWUMBj1KRyLN3XxoYIeLYfADB3TgfyWIQAtKaiiZKRPqTMKUh/LhwMfCe0VqbBEuOuFghe7jrBwWHFPn6bgs/dFmv+g9PbkLVPJGYLLduu7eJBdQIoQjFaxbEzm6QslodfKlyzXw/ZU+Zpw7LLVwBRl47v1za0ASiOC6XfN8CzDlLPXtvb/I4Wxqe1v34VjUAeP1KpgrRz3GevMjNL4RZ4EydUJsF111rJhWU="
- secure: "t6A/3x++oXY7FbJxtOPA63X2aWBIwAGrsPssm8G3nQKdzrklCVouVniN2R2LU9gylMB+bQotHrLm+2IeRNmL9ccV5zcMKgpYBc8Y8JKcx5Tzz0LPxdAf2rBgdwUlXZkwluu3A/1CVTOkkHp6lvNHHiuYi768LoVazMHu3fPl4meF6r6jD3CgZFnjkX8jFRetzol/XXAi58BHbV0r6XViVVt554K5Px9CUGvA9t97P6B4aUQzdY09/8JyQQGrd321jmZPIkugO1CUSCKV8UGeiZRKE2UEARB2Hsjy2N+esbfF79mhlsEuJGzXOVHlG/AdEYtJFs2D95MsuMpIJrXZnaUwJgTsM2A4b7kAwHCbDW2EyEJannSWqpqMCHsA4Jq4Hro+IbjvpzqfG3Rtv5x4WG81R5ouh7H6sEPKICzS3z6Q2jJbH1/x66pAyygeLso8iLlQmOhWsW63EsQOOzUrOmlhGEEUFlRr8YfgPrKp5bSAVdzBUaEt6zG43xkhFntWhJW820rhG0K9qiNMuGnblesdJO8eFT05GjKZHnPy1tPe/aMXOFoiJcic5KPa2NKJRipGau3tAwFexZCKWb+ifSRkM3U5FAjpPLrBou80wIqEasdYvn25G/hFkR8XT09c79hdLLIXz/MGSMlHvzhHdCoWQ+/2woZ1cYvx4LoHS9g="
- COMMIT=${TRAVIS_COMMIT::8}

services:
- docker

before_install:
- docker build -t web-login-site/web-login-site .
- docker run -dt -p 127.0.0.1:443:443 web-login-site/web-login-site
- docker ps -a
- docker run web-login-site/web-login-site /bin/sh -c "npm test"

script:
- echo Test
- echo Home $HOME
- set
- echo $TENABLE_IO_CONTAINER_SECURITY_EMAIL
- echo $TENABLE_IO_CONTAINER_SECURITY_PASSWORD
- exit 1

after_success:
- docker login -u $TENABLE_IO_CONTAINER_SECURITY_EMAIL -p $TENABLE_IO_CONTAINER_SECURITY_PASSWORD registry.cloud.tenable.com
- export REPO=web-login-site/web-login-site
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO