sudo: required
language: node_js

services:
- docker

before_install:
- docker build -t web-login-site/web-login-site .
- docker run -dt -p 127.0.0.1:443:443 web-login-site/web-login-site
- docker ps -a

after_success:
- docker login -u $TENABLE_IO_ACCESS_KEY -p $TENABLE_IO_SECRET_KEY registry.cloud.tenable.com
- export REPO=web-login-site/web-login-site
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO