sudo: required
language: node_js

env:
global:
- secure: "tIOg6Zk9V/VzmMRUV15X7evUm6vRdM7PHOxAeCrRFB7aD+uze23xs/uqletkcejtLIHFZRk1FiuzhJUHCKkvSGoVLzsmceQP0RWg5jV8GeCL+Ft64Mj75AZizjfO0Ytwc/ERj+fCBehxZl/lbgfZnhMnrtFm/bjPrLBD2TfvHUIVnAv+MdArOhENa9xtw2KEYhlJ7b6oaPsykRbo0xnFX/pYKy5UWLC31S4VhmMAb+FHRYkwAGNF9cb8f5Ijy/7XNQ7j8U/9EHX9EaXslTtZ7xWt0ligdtRfT+dtJ8iShrOQb5wF0wzfpfgBeE+G7I9CjId24frx7PqfzOs7hiUdXZhhJEfyILfs4NDjzjogARe29X6McfF/STrzgnYSMT41NrWugqawTbpPm/3CzSoLGntACvoA+ylwdhRpBXJaKYq88AE/Bmz8YmqVk2sDQqgbYUjT0dp3J32Woeb9ftlmB94WeJXhheRHC96VW8lCgWE0zp+S9CuAiDm9myXnlWdeBaDI98BGkU4F58MzrUoBxQm0uXT/ahvjPPvsuySuZw08YGzBqTBeGDSySH3E6Ucnn1WSOEwKF+pGWx0VUC03NSdzdetvejLQKd7OWhNn9jc2sQ44jCZri8Z97CG12y6neWJYpUygj5Tni3QJtpZECkItJUQgXtNLk9dxbQ7CKhA="
- secure: "ZV4Rf7zFCnbYauko6ZLQgqP3cAjbv7hYz2tIeJKlFZQrr5sTs4HrzAA/ZrHG8dCNeTZNCyUr3Ndbk6X1BLAjgwTTxaWYlUSl7mQiTdrBYPIa2a0ASLyP6GK6fXTRRhui5BDRPJWu/Tk72Qdiu1dghQp3UjCCklCZ0uy5zn/N7FCMCMQNXqlwB4HR8XkTknbFKu+mend4GAl1HVOy0zlDbQhnpxz7fI/Xk67yd0ETucNm37GoLF7sQczbiV6sp3r7jUImobB37gEIV0sMiBQGxGuCq/DqFo7fRlpQYz9otj88mjhkjuj2bHFLUOF7t4UK5fM+uzSJF5P5oSy7id9zVxdPO5AyNKQkBXiDgKbOtonfwVH613lp3Zckls/9q5FMYWFcQgQzNv+Y6iUPjNLadqaer65NnkkEIRiZvlXwUajCoee9JN0qcyh8udRH+U1dds3ZE8sWskLhD578uUUpHBNVMmHZv5+oMluGMMZgsP/dCG7jJqPEVIYyqoraCoDXHY3i3njSDWznDrFFf+/mZxcsxJBwszC1JuyQnFZ1ihqoYHkfso4BAr8im/N4VZhX1jSIDBy8Yo1SMuHA5aidHxqp37zSi/P4Ids71lcqdNPOwZQLxaGDBMv2cQH0WLMHNwIVle7An41zCWEWZHjx5Kogp7s0LCwa0yV8qYMkw6o="
- COMMIT=${TRAVIS_COMMIT::8}

services:
- docker

before_install:
- docker build -t web-login-site/web-login-site .
- docker run -dt -p 127.0.0.1:443:443 web-login-site/web-login-site
- docker ps -a
- docker run web-login-site/web-login-site /bin/sh -c "npm test"

script:
- echo Test
- echo Home $HOME
- set
- echo $TENABLE_IO_CONTAINER_SECURITY_EMAIL
- echo $TENABLE_IO_CONTAINER_SECURITY_PASSWORD
- exit 1

after_success:
- docker login -u $TENABLE_IO_CONTAINER_SECURITY_EMAIL -p $TENABLE_IO_CONTAINER_SECURITY_PASSWORD registry.cloud.tenable.com
- export REPO=web-login-site/web-login-site
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO