sudo: required
language: node_js
env:
  global:
  - secure: eLfK8uHn09xLj4opsOYg3++uOhWbna0Q+xKZexAc5RR3TuMycXidN8yW+XYCKlTdoTOyH9R1cgprbnch3xgOXgdq8mwWwHv7N6f65m1+I1ucucWDH8MgOdzvzwq1URqlQy/nwdnqd9G+r1/avC8bSHv9mIr/rmvMyEPzqDJ1VgrXj0QO8b1ZCd4uBIgIFPB0MRvNAyuoutr7xnkokS+MlHF4x2QA/yYPQVZf4UbjARCO/+Z/L31DFbzZ4HNVfzufqrALYruA4EoiLpJ6+t2ABIAWHoPF2SiAkyk1HGwecZ5+EiU9+PjnupusBZBPsusbVWeUGAZZEZaMbZI0GH2SOfkLdNs7sFBzuv/Jtt6+tC4qTnqsekSCz8xmiloPkvpUnHwzJo5xQSCQvY0Ub/cr5+vVei79w1QH09tCtTL5S3Zv1gBQ8qVV3cOUyQmHqc3ee7pB54osnzRtDUVreCeJHTLls3lMgfJG+ygDUexqGlhpt1SFInvOJFCC8hBkayXYYPjUjy/lqkWGGVuoVKdWrQ82ytp5kcMASxymHa11m4wq/KIlVFRUuuB8kAP+OsfVbLC20jsUcJK2k9Z/0qIe+IxePzLe5O4jM5QntBR7vTIVgSmeBjMjaFkRh0o6r3rSAOHCWBdXpjyJKo9A7+OcF59MoBMiN/0RLXtPHuzU3lY=
  - secure: NJnI+/JwxHYfGOEiVKQfmpJJnm8mZF2oly8Be9Hz1gJLygwX6BGgKMMgx2udJtx9VQF5X3ujxG+C5U3g9S28efR0QN4ygi1pedRgq5h0e7Vctb+UW9ppwRY+BGsRUPfFS53jMegW7Pkxx1VosTKERMQc6zCPbY+nhzCwYmrRs4Tm7aKqVRYCzpel33BGuRbiZiyzHBAPS2J4PMw1JGfg8ty/0xzfS5uk/cTtKXZN6ELXQFaRvMft8O+XM043eSg2rm8gdDxTgTIp5awDNBxqnep2Ew3OdhU3bIoRL9l4gozsJeb7WiL/6nROIdI5q4eK9nldFbAZaE10AeSNvUgxdxZbS9NF5nUC38cCIS+m2eHnS/1AQxisV7BvsEHVdNsHA90+e9ti7sDpLEgeBXNcdQvr7DYBLQUfXKsxhyz7PBZneUUPgopDqU7hWG3dQMd8G5SwWVdAzUfWtTECrPUXNN2HZnIieXykOImJNr9pQz3khjVMqBi81FV8QDGWZF5j1ruuIQAc27S5KM1ieYlCARQ3xSyVXxYSSg47gNE8XVBku4XyfmCVPGg+fcQZ6E1GDdkKpvH+IdlbrW9/h0xPSYtJG82WMUbVMItYHPA1zGMx04jrRadHxa3EfUksj2A27qP9UJspG6tLCzrDpvrwstctThoLSs3K0yc7XBlHDjo=
  - secure: KQj6ht5pRm6iipNe5ZolEHzxUf7dxlFcDp93A3QgieCfyPTLkhiP4jpJ1BRCMZhrHcDvSgnfvhzeR7x6f3mSRv66X58Rl/EslBWAafRYmmSwtBTe3K5IChiX3ehhdrR2M+Fcojvlt0HHuAyIS5a3RkhBoyWsrhKQwmydyqWuR6JFm1vH5O2IbNqse2JV36fhxkzvOQq7HMuvpek+Zz0gG9839NoO6Q64sFRmY7VgloOOOlM2g7wm/lEQq/+6ERPBgQ8KLzfxT3hB9Agn9KPkxiJoK+sgNbRF7mDHmyBj1geiaEJhMPeRwfYlhDs8dqiLyNHJSmAujumORqQ230VtmVOXFUu5X0YvrJ6VkNEcXJ4okmIaTczjur0jlZITCahG1EAMrZ+uitRRtU3Vky6Kd/DdbsXhIl+WtiRgCq1MYcytcEzPo9lVH6Css8wUEMhrJrJ2tlIWAkqNaxMHOQ0K65oUAmFhvggkV/LZy9iVQF7bXlWGokmywDYdKFDp2Go8r+hjFxgAu8MBkQKM5u5lC2OVqRi3oZhdtdcQLNCjNOhORlKAD63lCO9pUvl3/LM8CeOW+8KjU+mf/bD0BQqcg2XDC7Al9KgLBOUBdJGvfRLTM6bEgk2Owm7AOXLxQZ7QOPOr5g/GXy49mykWf6USVSK8pM2bzGq+VqVlMURuji4=
  - COMMIT=${TRAVIS_COMMIT::8}
services:
- docker
before_install:
- docker build -t web-login-site/web-login-site .
- docker run -dt -p 127.0.0.1:443:443 web-login-site/web-login-site
- docker ps -a
- docker run web-login-site/web-login-site /bin/sh -c "npm test"
script:
- echo Test
- echo Home $HOME
- echo $TENABLE_IO_CONTAINER_SECURITY_EMAIL
- echo $TENABLE_IO_CONTAINER_SECURITY_PASSWORD
- exit 1
- set
after_success:
- docker login -u $TENABLE_IO_CONTAINER_SECURITY_EMAIL -p $TENABLE_IO_CONTAINER_SECURITY_PASSWORD
  registry.cloud.tenable.com
- export REPO=web-login-site/web-login-site
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
