sudo: required
language: node_js

env:
global:
- secure: "ALgTFpMbPi4Yd1pyyYJGcJKidmZqt0wOlBV9CxJCqP5vm3NcMaUGJBvOQel0K/Kyxf9OesNLd8cJesjPjAcxbFpiIQnPb6tBB08biZ/8PBUpsPwB4a95dGXvc/y+CNiLnJgqT2lqDuo8NlQdTKiyDuir64Q4I+e3MeVVaR06G+codfuJln13Cl30ig8wtpbJ6IkEwJhk16S5FFvzNlTsC+wFjM6e9YoM1sYmPMX09BBaXMTWsyOb+hhkmcQGkFhLQ4vC7T5FIoBjpkTrtLH9qRpo6lX1DJSC2KjLF/2ywoGEsDBum92T8aIZ7H95GgGmg69k4/7M8xhpd03tGJZmU5fPeqZEi3o7w6paLtVi2R25H2MSq0SbAvQfxynuv+8BOj9pCWLpRfMljifw59gnUGvzW6BWCDI4/kWaJM2jOAQmkHitRQOKuKSPlyY7TJAz5pXBSR3dTCSz7XUqEjRc87pQIK3c1JAkcf9LR1hN2gEtdKpFqYL90E4EKKC4Y7YU75z4tcFGkv0GYcul0oSVNQ1wygYeslUm3ksaa9s50Nvc+N2iBsQGYvBdOwyeo742SufDBoHXn/w1qFa7Yt9KoUUx0PEI96scVXO0mNArCtthNjdk0cWr1J1mjplvPud6UKgd7hUZr6c0AEwKSPPhgBcyJWC0hXbESwKtvTfu2LU="
- secure: "eFCmNW7SVJgj87ya5LcDmWi/NFHXVFhLeui6YXUqDflqMN9dX6ldYaZySB6XdwxLtO5GF43fnYcGPd4Z1/d+GZWWDEuXJPjez8wXVSIH9Eupj3Uexb/iT8Ixw5PkHkQEmBJThgI1ft39RBm8caNTLoZAWQ7VOV3KpJmKYaj5nCvnUI5gDSLNBK7+x2klZ3EBLFx+EpAuEjEW07yb/bq8+CfSacfaxVqcuaIOOn9CpD8dy3Ha20BXXmT+pE9tpi99XpBaAs4sRah+FT+kKGnIrsZd8WqhlFH8A1j7i3vGyTTqwVP7BV0iYQBobA6Tkw2YWQHaE2qDqjWIAfDCgR64USjJjxpA/rNCrooFsic6OHhe95GCacl5wJ3hVXFQAhqSDoQ4jTtvLHhtdHPaiZPY9oHCA4PwhPnso9fAtoigfpw8QyoSVrNFxeeWuxpYFS8Fo1CF0bCGPitBPDbNxQLqJ6apknSs5WcA8cPtpe5TMR9Wev5t3WnqTcfICn9gKYSu/4TKkRPlPOHqqoPfYIJcf75d6gD/Y0k1FMKfP+QFdp/cmMPsfgT7f12cZVTK1iirXlTeaOm+Q8C4KKy6cs+WZA8kDA/zdGAy6JV1dQUhvAm4ih+HgUTNv2+UpyhzzPhwTN+K5e0lIxHyVxJgnHgJshmgQ1NXYunIESrKfztOkBY="
- secure: "DFopaaAknT0mJck67XkNtmUofzby5q1woP1S1h9I9zgD7dYIrrZZ0wCsOov4YiKtgOu0yh6uzz1z/2ie0JraqKykPER6Z32LuantgBziHjL/4a/XYV2QNVMtUNP9MO5AUiWFAwBHQY/AgVZkOaKHjclbWT+rSmTnfbtocsaK16RWFpLY9NTDgEPeMWilTYCJR6ZKwwGukqdedeWSKPzWOtLx5iHefpBTl4pzjy1ZtUELWHytX8eF/OZRQrlaT5mOWV8kIft7UblXrsL10K+MKx9+l2iBtaoxMmsb1Z6VjlnyOoiDSoW3fJJs5rSyQZ1QQzw2Bslj5tnUoEDSWP5a2IHHqBAmMS85QKtzSOQzahre4hQOq1SBHal3xDyXpKttXJYjLMGpMIVIXjSCQtDhMUF/p0PcWbxBaUN9Swl5KkijiXimnZyuT6vOD1Qedhxv3et3b2LlexlF80luwSyEkO3rFpQON5wYfS4dS7MN+PQ28JyLBr/gq5rDqAAYigrWHwEVCm8YQRRjcpJJbG9BxBZ4XWFU+8fbQc9/nHUHTiTbgziojrE/YyITangym1WKJfBVVujvFhfkLCwt1XJxjgdNWPUyT/IW/8Q5aVabYQRTSXlwE/hVmXen+eJMqzAlj/bXVHahDV4F/IHnOSvdYn91nXrSHzsAborOBXfDQHo="
- COMMIT=${TRAVIS_COMMIT::8}

services:
- docker

before_install:
- docker build -t web-login-site/web-login-site .
- docker run -dt -p 127.0.0.1:443:443 web-login-site/web-login-site
- docker ps -a
- docker run web-login-site/web-login-site /bin/sh -c "npm test"

script:
- echo

after_success:
- docker login -u $TENABLE_IO_ACCESS_KEY -p $TENABLE_IO_SECRET_KEY registry.cloud.tenable.com
- export REPO=web-login-site/web-login-site
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO